Introducing multi-value indexing to FLAT algorithm
RedisAI/VectorSimilarity pull request #204
Opened 2022-08-14 13:03 UTC by GuyAv46

**Describe the changes in the pull request**

This PR introduces the `BruteForceIndex_Multi` class, which supports multi-value indexing under the same label. Any call to `VecSimIndex_Add` with this instance and an existing label in the index, will result in another vector under the same label. The "delete" function will delete all vectors under the given label.

**Main objects this PR modified**
1. adds a new `BruteForceIndex_Multi` class that supports multi-value indexing with the FLAT algorithm.

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

2022-08-16 09:08 UTC, meiravgri reviewed
cool :) :+1:

2022-08-16 09:08 UTC, meiravgri commented on tests/unit/test_bruteforce_multi.cpp
> +    for (size_t i = 0; i < 4; i++) {
what does this check? labels 0,3 are invalid

2022-08-16 09:08 UTC, meiravgri commented on tests/unit/test_bruteforce_multi.cpp
> +TEST_F(BruteForceMultiTest, brute_get_distance) { // TODO: modify to use multi values
TODO?

2022-08-17 10:11 UTC, GuyAv46 commented on src/VecSim/algorithms/brute_force/brute_force_multi.cpp
> +    auto &labelKey = labelToIdsLookup.at(label);
It is not really possible to have a missing id like that, but I guess it's OK to check.

2022-08-17 11:14 UTC, GuyAv46 commented on src/VecSim/algorithms/brute_force/brute_force_multi.cpp
> +        ret = (removeVector(id_to_delete) && ret);
@DvirDukhan WDYT? I guess it's true but maybe in the future it won't be?  is returning an "and" result will be good if the delete function could return false?

2022-08-17 11:15 UTC, GuyAv46 commented on src/VecSim/algorithms/brute_force/brute_force_multi.cpp
> +        labelToIdsLookup.emplace(label, vecsim_stl::vector<idType>{1, id, this->allocator});
Thanks! :sunglasses:

2022-08-17 11:36 UTC, GuyAv46 commented on tests/unit/test_bruteforce_multi.cpp
> +TEST_F(BruteForceMultiTest, test_delete_swap_block) {
What is the special case in more than one swap?

2022-08-17 12:01 UTC, GuyAv46 commented on tests/unit/test_bruteforce_multi.cpp
> +TEST_F(BruteForceMultiTest, brute_get_distance) { // TODO: modify to use multi values
good point. done :)

2022-08-17 15:03 UTC, meiravgri approved these changes
2 small notes, 
other than that approved
very nice :)

2022-08-22 06:55 UTC, DvirDukhan requested changes

2022-08-22 06:55 UTC, DvirDukhan commented on src/VecSim/algorithms/brute_force/brute_force_multi.cpp
> +    auto &labelKey = labelToIdsLookup.at(label);
```suggestion
    auto &ids= labelToIdsLookup.at(label);
```

2022-08-22 06:55 UTC, DvirDukhan commented on tests/unit/test_bruteforce_multi.cpp
> +TEST_F(BruteForceMultiTest, resizeNAlignIndex) {
good test, please check also the number of actual blocks, not only meta data containers

2022-08-22 06:55 UTC, DvirDukhan commented on tests/unit/test_bruteforce_multi.cpp
> +// TEST_F(BruteForceMultiTest, brute_force_vector_search_test_ip) {
comments?

2022-08-22 06:55 UTC, DvirDukhan commented on tests/unit/test_bruteforce_multi.cpp
> +    ASSERT_TRUE(k);
why we need this line?

2022-08-22 06:55 UTC, DvirDukhan commented on tests/unit/test_bruteforce_multi.cpp
> +        .hnswParams = HNSWParams{
bfParams?

2022-08-22 07:30 UTC, GuyAv46 commented on tests/unit/test_bruteforce_multi.cpp
> +        .hnswParams = HNSWParams{
good catch thanks!

2022-08-22 08:30 UTC, DvirDukhan approved these changes

2022-08-22 08:45 UTC, merged