Fp64 dist func sse
RedisAI/VectorSimilarity pull request #239
Opened 2022-09-11 15:40 UTC by meiravgri

2022-09-18 12:51 UTC, alonre24 reviewed
Looks good!! Only had small questions regarding tests and coverage - (applies to all tests in test_spaces file)

2022-09-18 12:51 UTC, alonre24 commented on tests/unit/test_spaces.cpp
> +    default:
What about the case of no optimization?

2022-09-18 12:51 UTC, alonre24 commented on tests/unit/test_spaces.cpp
> +        ;
redundant semi colon ;)

2022-09-18 12:51 UTC, alonre24 commented on src/VecSim/spaces/spaces.cpp
> +        ret_score = ITER_512_BITS;
Why there is no coverage for this?

2022-09-18 15:45 UTC, alonre24 approved these changes

2022-09-21 06:26 UTC, DvirDukhan requested changes

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.cpp
> +    ITER_512_BITS = 1,          // FP32 -> dim % 16 == 0, FP64 -> dim % 8 == 0
```suggestion
   512_BITS = 1,          // FP32 -> dim % 16 == 0, FP64 -> dim % 8 == 0
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.h
> +    ITER_512_BITS = 1, // FP32 -> dim % 16 == 0, FP64 -> dim % 8 == 0
```suggestion
    512_BITS = 1, // FP32 -> dim % 16 == 0, FP64 -> dim % 8 == 0
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.h
> +    ITER_128_BITS = 2, // FP32 -> dim % 4 == 0, FP64 -> dim % 2 == 0
```suggestion
    128_BITS = 2, // FP32 -> dim % 4 == 0, FP64 -> dim % 2 == 0
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.h
> +    ITER_512_BITS_RESIDUALS =
```suggestion
    512_BITS_RESIDUALS =
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.h
> +
not in use

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.h
> +    ITER_128_BITS_RESIDUALS = 4, // FP32 ->dim > 4, FP64 -> dim > 2
```suggestion
    128_BITS_RESIDUALS = 4, // FP32 ->dim > 4, FP64 -> dim > 2
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/L2/L2_SSE_FP64.cpp
> +    // Calc how many doubles we can calc using 512 bits iterations.
```suggestion
    // Calculate how many doubles we can calculate using 512 bits iterations.
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/L2/L2_SSE_FP64.cpp
> +    // Calc the rest using a brute force function
```suggestion
    // Calculate the rest using the basic function
```

2022-09-21 06:26 UTC, DvirDukhan commented on src/VecSim/spaces/L2/L2_SSE_FP64.cpp
> +    // Calc how many doubles we can calc using 512 bits iterations.
```suggestion
    // Calculate how many doubles we can calculate using 512 bits iterations.
```

2022-09-21 10:24 UTC, DvirDukhan commented on src/VecSim/spaces/spaces.h
> +    SPLIT_TO_128_BITS_WITH_RESIDUALS = 4, // FP32 ->dim > 4, FP64 -> dim > 2
```suggestion
    SPLIT_TO_512_128_BITS_WITH_RESIDUALS = 4, // FP32 ->dim > 4, FP64 -> dim > 2
```

2022-09-21 11:13 UTC, merged